"""empty message

Revision ID: 94db121aa582
Revises: 
Create Date: 2020-04-17 16:32:57.849576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94db121aa582'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('saldo', sa.String(length=20), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_contas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('lancamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=64), nullable=False),
    sa.Column('data_lanc', sa.DateTime(), nullable=False),
    sa.Column('valor', sa.String(length=20), nullable=False),
    sa.Column('debito_id', sa.Integer(), nullable=True),
    sa.Column('credito_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credito_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['debito_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lancamentos')
    op.drop_table('contas')
    op.drop_table('tipo_contas')
    # ### end Alembic commands ###
